name: 'Colab Badge Action'
author: trsvchn
description: 'Inserts/Updates Colab Badges within Jupyter Notebooks'

inputs:
  github_token:
    description: 'GITHUB_TOKEN secret'
    required: true
  check:
    description: 'Which notebooks to check: all or just committed: all | latest'
    default: 'all'
    required: false
  update:
    description: 'Update badges. Only badges added by this action will be updated'
    default: true
    required: false
  target_branch:
    description: 'Branch that the badge will target. Defaults to the current branch.'
    default: ''
    required: false
  target_repository:
    description: 'Repository that the badge will target. Defaults to the current repository.'
    default: ''
    required: false

outputs:
  modified_notebooks:
    description: 'String of modified notebooks file names, separated by whitespace, e.g. "nb1.ipynb nb2.ipynb nb3.ipynb"'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'git-pull-request'
  color: 'yellow'
